package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 22, 2022, 1:51:59 AM by Hibernate Tools 5.6.7.Final

/**
 * Credentials generated by hbm2java
 */
public class Credentials implements java.io.Serializable {

	private int employeeId;
	private Employees employees;
	private String username;
	private String password;

	public Credentials() {
	}

	public Credentials(Employees employees, String username, String password) {
		this.employees = employees;
		this.username = username;
		this.password = password;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
