package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 11, 2022, 11:53:45 PM by Hibernate Tools 5.6.7.Final

/**
 * DealsPhoneNumber generated by hbm2java
 */
public class DealsPhoneNumber implements java.io.Serializable {

	private DealsPhoneNumberId id;
	private Deals deals;

	public DealsPhoneNumber() {
	}

	public DealsPhoneNumber(DealsPhoneNumberId id, Deals deals) {
		this.id = id;
		this.deals = deals;
	}

	public DealsPhoneNumberId getId() {
		return this.id;
	}

	public void setId(DealsPhoneNumberId id) {
		this.id = id;
	}

	public Deals getDeals() {
		return this.deals;
	}

	public void setDeals(Deals deals) {
		this.deals = deals;
	}

}
