package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 11, 2022, 11:53:45 PM by Hibernate Tools 5.6.7.Final

/**
 * DealsPhoneNumberId generated by hbm2java
 */
public class DealsPhoneNumberId implements java.io.Serializable {

	private String phoneNumber;
	private int dealsId;

	public DealsPhoneNumberId() {
	}

	public DealsPhoneNumberId(String phoneNumber, int dealsId) {
		this.phoneNumber = phoneNumber;
		this.dealsId = dealsId;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public int getDealsId() {
		return this.dealsId;
	}

	public void setDealsId(int dealsId) {
		this.dealsId = dealsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DealsPhoneNumberId))
			return false;
		DealsPhoneNumberId castOther = (DealsPhoneNumberId) other;

		return ((this.getPhoneNumber() == castOther.getPhoneNumber()) || (this.getPhoneNumber() != null
				&& castOther.getPhoneNumber() != null && this.getPhoneNumber().equals(castOther.getPhoneNumber())))
				&& (this.getDealsId() == castOther.getDealsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode());
		result = 37 * result + this.getDealsId();
		return result;
	}

}
