package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 22, 2022, 1:51:59 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Deals generated by hbm2java
 */
public class Deals implements java.io.Serializable {

	private int dealsId;
	private Employees employees;
	private Projects projects;
	private Date timeCreated;
	private String buyerName;
	private String email;
	private int downPayment;
	private String phone;
	private Set descriptions = new HashSet(0);

	public Deals() {
	}

	public Deals(int dealsId, Employees employees, Projects projects, Date timeCreated, String buyerName, String email,
			int downPayment) {
		this.dealsId = dealsId;
		this.employees = employees;
		this.projects = projects;
		this.timeCreated = timeCreated;
		this.buyerName = buyerName;
		this.email = email;
		this.downPayment = downPayment;
	}

	public Deals(int dealsId, Employees employees, Projects projects, Date timeCreated, String buyerName, String email,
			int downPayment, String phone, Set descriptions) {
		this.dealsId = dealsId;
		this.employees = employees;
		this.projects = projects;
		this.timeCreated = timeCreated;
		this.buyerName = buyerName;
		this.email = email;
		this.downPayment = downPayment;
		this.phone = phone;
		this.descriptions = descriptions;
	}

	public int getDealsId() {
		return this.dealsId;
	}

	public void setDealsId(int dealsId) {
		this.dealsId = dealsId;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	public String getBuyerName() {
		return this.buyerName;
	}

	public void setBuyerName(String buyerName) {
		this.buyerName = buyerName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getDownPayment() {
		return this.downPayment;
	}

	public void setDownPayment(int downPayment) {
		this.downPayment = downPayment;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getDescriptions() {
		return this.descriptions;
	}

	public void setDescriptions(Set descriptions) {
		this.descriptions = descriptions;
	}

}
