package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 11, 2022, 11:53:45 PM by Hibernate Tools 5.6.7.Final

import java.util.Date;

/**
 * Description generated by hbm2java
 */
public class Description implements java.io.Serializable {

	private int descriptionId;
	private Deals deals;
	private Leads leads;
	private Status status;
	private Date timeCreated;
	private String notes;

	public Description() {
	}

	public Description(int descriptionId, Leads leads, Status status, Date timeCreated, String notes) {
		this.descriptionId = descriptionId;
		this.leads = leads;
		this.status = status;
		this.timeCreated = timeCreated;
		this.notes = notes;
	}

	public Description(int descriptionId, Deals deals, Leads leads, Status status, Date timeCreated, String notes) {
		this.descriptionId = descriptionId;
		this.deals = deals;
		this.leads = leads;
		this.status = status;
		this.timeCreated = timeCreated;
		this.notes = notes;
	}

	public int getDescriptionId() {
		return this.descriptionId;
	}

	public void setDescriptionId(int descriptionId) {
		this.descriptionId = descriptionId;
	}

	public Deals getDeals() {
		return this.deals;
	}

	public void setDeals(Deals deals) {
		this.deals = deals;
	}

	public Leads getLeads() {
		return this.leads;
	}

	public void setLeads(Leads leads) {
		this.leads = leads;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
