package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 22, 2022, 1:51:59 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Developers generated by hbm2java
 */
public class Developers implements java.io.Serializable {

	private int developersId;
	private String name;
	private String phoneNumber;
	private String email;
	private Date dateOfContract;
	private String address;
	private Set projectses = new HashSet(0);

	public Developers() {
	}

	public Developers(int developersId, String name, String phoneNumber, String email, Date dateOfContract) {
		this.developersId = developersId;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.dateOfContract = dateOfContract;
	}

	public Developers(int developersId, String name, String phoneNumber, String email, Date dateOfContract,
			String address, Set projectses) {
		this.developersId = developersId;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.dateOfContract = dateOfContract;
		this.address = address;
		this.projectses = projectses;
	}

	public int getDevelopersId() {
		return this.developersId;
	}

	public void setDevelopersId(int developersId) {
		this.developersId = developersId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDateOfContract() {
		return this.dateOfContract;
	}

	public void setDateOfContract(Date dateOfContract) {
		this.dateOfContract = dateOfContract;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set getProjectses() {
		return this.projectses;
	}

	public void setProjectses(Set projectses) {
		this.projectses = projectses;
	}

}
