package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 22, 2022, 1:51:59 AM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
public class Employees implements java.io.Serializable {

	private int employeesId;
	private Gender gender;
	private Jobs jobs;
	private long ssn;
	private String FName;
	private String LName;
	private String phoneNumber;
	private String qualifications;
	private String address;
	private int salary;
	private Set dealses = new HashSet(0);
	private Set jobHistories = new HashSet(0);
	private Credentials credentials;
	private Set leadses = new HashSet(0);

	public Employees() {
	}

	public Employees(int employeesId, Gender gender, Jobs jobs, long ssn, String FName, String LName,
			String phoneNumber, String qualifications, int salary) {
		this.employeesId = employeesId;
		this.gender = gender;
		this.jobs = jobs;
		this.ssn = ssn;
		this.FName = FName;
		this.LName = LName;
		this.phoneNumber = phoneNumber;
		this.qualifications = qualifications;
		this.salary = salary;
	}

	public Employees(int employeesId, Gender gender, Jobs jobs, long ssn, String FName, String LName,
			String phoneNumber, String qualifications, String address, int salary, Set dealses, Set jobHistories,
			Credentials credentials, Set leadses) {
		this.employeesId = employeesId;
		this.gender = gender;
		this.jobs = jobs;
		this.ssn = ssn;
		this.FName = FName;
		this.LName = LName;
		this.phoneNumber = phoneNumber;
		this.qualifications = qualifications;
		this.address = address;
		this.salary = salary;
		this.dealses = dealses;
		this.jobHistories = jobHistories;
		this.credentials = credentials;
		this.leadses = leadses;
	}

	public int getEmployeesId() {
		return this.employeesId;
	}

	public void setEmployeesId(int employeesId) {
		this.employeesId = employeesId;
	}

	public Gender getGender() {
		return this.gender;
	}

	public void setGender(Gender gender) {
		this.gender = gender;
	}

	public Jobs getJobs() {
		return this.jobs;
	}

	public void setJobs(Jobs jobs) {
		this.jobs = jobs;
	}

	public long getSsn() {
		return this.ssn;
	}

	public void setSsn(long ssn) {
		this.ssn = ssn;
	}

	public String getFName() {
		return this.FName;
	}

	public void setFName(String FName) {
		this.FName = FName;
	}

	public String getLName() {
		return this.LName;
	}

	public void setLName(String LName) {
		this.LName = LName;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getQualifications() {
		return this.qualifications;
	}

	public void setQualifications(String qualifications) {
		this.qualifications = qualifications;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getSalary() {
		return this.salary;
	}

	public void setSalary(int salary) {
		this.salary = salary;
	}

	public Set getDealses() {
		return this.dealses;
	}

	public void setDealses(Set dealses) {
		this.dealses = dealses;
	}

	public Set getJobHistories() {
		return this.jobHistories;
	}

	public void setJobHistories(Set jobHistories) {
		this.jobHistories = jobHistories;
	}

	public Credentials getCredentials() {
		return this.credentials;
	}

	public void setCredentials(Credentials credentials) {
		this.credentials = credentials;
	}

	public Set getLeadses() {
		return this.leadses;
	}

	public void setLeadses(Set leadses) {
		this.leadses = leadses;
	}

}
