package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 22, 2022, 1:51:59 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;

/**
 * JobHistory generated by hbm2java
 */
public class JobHistory implements java.io.Serializable {

	private int jobHistoryId;
	private Employees employees;
	private Jobs jobs;
	private Date startDate;
	private Date endDate;

	public JobHistory() {
	}

	public JobHistory(int jobHistoryId, Employees employees, Jobs jobs, Date startDate) {
		this.jobHistoryId = jobHistoryId;
		this.employees = employees;
		this.jobs = jobs;
		this.startDate = startDate;
	}

	public JobHistory(int jobHistoryId, Employees employees, Jobs jobs, Date startDate, Date endDate) {
		this.jobHistoryId = jobHistoryId;
		this.employees = employees;
		this.jobs = jobs;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public int getJobHistoryId() {
		return this.jobHistoryId;
	}

	public void setJobHistoryId(int jobHistoryId) {
		this.jobHistoryId = jobHistoryId;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public Jobs getJobs() {
		return this.jobs;
	}

	public void setJobs(Jobs jobs) {
		this.jobs = jobs;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
