package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 22, 2022, 1:51:59 AM by Hibernate Tools 5.6.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Leads generated by hbm2java
 */
public class Leads implements java.io.Serializable {

	private int leadsId;
	private Employees employees;
	private Source source;
	private Date timeCreated;
	private String clientName;
	private String email;
	private String request;
	private String phone;
	private Set descriptions = new HashSet(0);

	public Leads() {
	}

	public Leads(int leadsId, Employees employees, Source source, Date timeCreated, String clientName, String email) {
		this.leadsId = leadsId;
		this.employees = employees;
		this.source = source;
		this.timeCreated = timeCreated;
		this.clientName = clientName;
		this.email = email;
	}

	public Leads(int leadsId, Employees employees, Source source, Date timeCreated, String clientName, String email,
			String request, String phone, Set descriptions) {
		this.leadsId = leadsId;
		this.employees = employees;
		this.source = source;
		this.timeCreated = timeCreated;
		this.clientName = clientName;
		this.email = email;
		this.request = request;
		this.phone = phone;
		this.descriptions = descriptions;
	}

	public int getLeadsId() {
		return this.leadsId;
	}

	public void setLeadsId(int leadsId) {
		this.leadsId = leadsId;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public Source getSource() {
		return this.source;
	}

	public void setSource(Source source) {
		this.source = source;
	}

	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRequest() {
		return this.request;
	}

	public void setRequest(String request) {
		this.request = request;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getDescriptions() {
		return this.descriptions;
	}

	public void setDescriptions(Set descriptions) {
		this.descriptions = descriptions;
	}

}
