package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 11, 2022, 11:53:45 PM by Hibernate Tools 5.6.7.Final

/**
 * LeadsPhoneNumberId generated by hbm2java
 */
public class LeadsPhoneNumberId implements java.io.Serializable {

	private String phoneNumber;
	private int leadsId;

	public LeadsPhoneNumberId() {
	}

	public LeadsPhoneNumberId(String phoneNumber, int leadsId) {
		this.phoneNumber = phoneNumber;
		this.leadsId = leadsId;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public int getLeadsId() {
		return this.leadsId;
	}

	public void setLeadsId(int leadsId) {
		this.leadsId = leadsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LeadsPhoneNumberId))
			return false;
		LeadsPhoneNumberId castOther = (LeadsPhoneNumberId) other;

		return ((this.getPhoneNumber() == castOther.getPhoneNumber()) || (this.getPhoneNumber() != null
				&& castOther.getPhoneNumber() != null && this.getPhoneNumber().equals(castOther.getPhoneNumber())))
				&& (this.getLeadsId() == castOther.getLeadsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode());
		result = 37 * result + this.getLeadsId();
		return result;
	}

}
