package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 11, 2022, 11:53:45 PM by Hibernate Tools 5.6.7.Final

/**
 * LeadsPhoneNumber generated by hbm2java
 */
public class LeadsPhoneNumber implements java.io.Serializable {

	private LeadsPhoneNumberId id;
	private Leads leads;

	public LeadsPhoneNumber() {
	}

	public LeadsPhoneNumber(LeadsPhoneNumberId id, Leads leads) {
		this.id = id;
		this.leads = leads;
	}

	public LeadsPhoneNumberId getId() {
		return this.id;
	}

	public void setId(LeadsPhoneNumberId id) {
		this.id = id;
	}

	public Leads getLeads() {
		return this.leads;
	}

	public void setLeads(Leads leads) {
		this.leads = leads;
	}

}
