package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 11, 2022, 11:53:45 PM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Projects generated by hbm2java
 */
public class Projects implements java.io.Serializable {

	private int projectsId;
	private Developers developers;
	private String name;
	private int unitPrice;
	private String location;
	private String type;
	private String commission;
	private Set dealses = new HashSet(0);

	public Projects() {
	}

	public Projects(int projectsId, Developers developers, String name, int unitPrice, String location, String type,
			String commission) {
		this.projectsId = projectsId;
		this.developers = developers;
		this.name = name;
		this.unitPrice = unitPrice;
		this.location = location;
		this.type = type;
		this.commission = commission;
	}

	public Projects(int projectsId, Developers developers, String name, int unitPrice, String location, String type,
			String commission, Set dealses) {
		this.projectsId = projectsId;
		this.developers = developers;
		this.name = name;
		this.unitPrice = unitPrice;
		this.location = location;
		this.type = type;
		this.commission = commission;
		this.dealses = dealses;
	}

	public int getProjectsId() {
		return this.projectsId;
	}

	public void setProjectsId(int projectsId) {
		this.projectsId = projectsId;
	}

	public Developers getDevelopers() {
		return this.developers;
	}

	public void setDevelopers(Developers developers) {
		this.developers = developers;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(int unitPrice) {
		this.unitPrice = unitPrice;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getCommission() {
		return this.commission;
	}

	public void setCommission(String commission) {
		this.commission = commission;
	}

	public Set getDealses() {
		return this.dealses;
	}

	public void setDealses(Set dealses) {
		this.dealses = dealses;
	}

}
