package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 22, 2022, 1:51:59 AM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Source generated by hbm2java
 */
public class Source implements java.io.Serializable {

	private int sourceId;
	private String name;
	private Set leadses = new HashSet(0);

	public Source() {
	}

	public Source(int sourceId, String name) {
		this.sourceId = sourceId;
		this.name = name;
	}

	public Source(int sourceId, String name, Set leadses) {
		this.sourceId = sourceId;
		this.name = name;
		this.leadses = leadses;
	}

	public int getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(int sourceId) {
		this.sourceId = sourceId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getLeadses() {
		return this.leadses;
	}

	public void setLeadses(Set leadses) {
		this.leadses = leadses;
	}

}
