package com.RealEstate.www._MySQL_DB_Entities;
// Generated May 22, 2022, 1:51:59 AM by Hibernate Tools 5.6.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private int statusId;
	private String name;
	private Set descriptions = new HashSet(0);

	public Status() {
	}

	public Status(int statusId, String name) {
		this.statusId = statusId;
		this.name = name;
	}

	public Status(int statusId, String name, Set descriptions) {
		this.statusId = statusId;
		this.name = name;
		this.descriptions = descriptions;
	}

	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDescriptions() {
		return this.descriptions;
	}

	public void setDescriptions(Set descriptions) {
		this.descriptions = descriptions;
	}

}
